-- Connect to exercises database
\c exercises

-- Create schemas for organizing exercise content by topic
CREATE SCHEMA IF NOT EXISTS basics;
CREATE SCHEMA IF NOT EXISTS advanced_queries;
CREATE SCHEMA IF NOT EXISTS query_planner;
CREATE SCHEMA IF NOT EXISTS optimization;
CREATE SCHEMA IF NOT EXISTS statistics;
CREATE SCHEMA IF NOT EXISTS operational_health;
CREATE SCHEMA IF NOT EXISTS indexes;
CREATE SCHEMA IF NOT EXISTS performance;
CREATE SCHEMA IF NOT EXISTS advanced_topics;
CREATE SCHEMA IF NOT EXISTS storage;
CREATE SCHEMA IF NOT EXISTS btree;
CREATE SCHEMA IF NOT EXISTS sorting;
CREATE SCHEMA IF NOT EXISTS transactions;
CREATE SCHEMA IF NOT EXISTS wal;
CREATE SCHEMA IF NOT EXISTS partitioning;
CREATE SCHEMA IF NOT EXISTS vacuum;
CREATE SCHEMA IF NOT EXISTS pgdog;
CREATE SCHEMA IF NOT EXISTS incidents;

-- Grant usage to learnpg user
GRANT ALL ON SCHEMA basics TO learnpg;
GRANT ALL ON SCHEMA advanced_queries TO learnpg;
GRANT ALL ON SCHEMA query_planner TO learnpg;
GRANT ALL ON SCHEMA optimization TO learnpg;
GRANT ALL ON SCHEMA statistics TO learnpg;
GRANT ALL ON SCHEMA operational_health TO learnpg;
GRANT ALL ON SCHEMA indexes TO learnpg;
GRANT ALL ON SCHEMA performance TO learnpg;
GRANT ALL ON SCHEMA advanced_topics TO learnpg;
GRANT ALL ON SCHEMA storage TO learnpg;
GRANT ALL ON SCHEMA btree TO learnpg;
GRANT ALL ON SCHEMA sorting TO learnpg;
GRANT ALL ON SCHEMA transactions TO learnpg;
GRANT ALL ON SCHEMA wal TO learnpg;
GRANT ALL ON SCHEMA partitioning TO learnpg;
GRANT ALL ON SCHEMA vacuum TO learnpg;
GRANT ALL ON SCHEMA pgdog TO learnpg;
GRANT ALL ON SCHEMA incidents TO learnpg;

-- Grant usage to learnpg_admin user
GRANT ALL ON SCHEMA basics TO learnpg_admin;
GRANT ALL ON SCHEMA advanced_queries TO learnpg_admin;
GRANT ALL ON SCHEMA query_planner TO learnpg_admin;
GRANT ALL ON SCHEMA optimization TO learnpg_admin;
GRANT ALL ON SCHEMA statistics TO learnpg_admin;
GRANT ALL ON SCHEMA operational_health TO learnpg_admin;
GRANT ALL ON SCHEMA indexes TO learnpg_admin;
GRANT ALL ON SCHEMA performance TO learnpg_admin;
GRANT ALL ON SCHEMA advanced_topics TO learnpg_admin;
GRANT ALL ON SCHEMA storage TO learnpg_admin;
GRANT ALL ON SCHEMA btree TO learnpg_admin;
GRANT ALL ON SCHEMA sorting TO learnpg_admin;
GRANT ALL ON SCHEMA transactions TO learnpg_admin;
GRANT ALL ON SCHEMA wal TO learnpg_admin;
GRANT ALL ON SCHEMA partitioning TO learnpg_admin;
GRANT ALL ON SCHEMA vacuum TO learnpg_admin;
GRANT ALL ON SCHEMA pgdog TO learnpg_admin;
GRANT ALL ON SCHEMA incidents TO learnpg_admin;

-- Set default permissions for learnpg
ALTER DEFAULT PRIVILEGES IN SCHEMA basics GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA advanced_queries GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA query_planner GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA optimization GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA statistics GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA operational_health GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA indexes GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA performance GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA advanced_topics GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA btree GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA sorting GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA transactions GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA wal GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA partitioning GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA vacuum GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgdog GRANT ALL ON TABLES TO learnpg;
ALTER DEFAULT PRIVILEGES IN SCHEMA incidents GRANT ALL ON TABLES TO learnpg;

-- Set default permissions for learnpg_admin
ALTER DEFAULT PRIVILEGES IN SCHEMA basics GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA advanced_queries GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA query_planner GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA optimization GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA statistics GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA operational_health GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA indexes GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA performance GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA advanced_topics GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA btree GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA sorting GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA transactions GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA wal GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA partitioning GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA vacuum GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgdog GRANT ALL ON TABLES TO learnpg_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA incidents GRANT ALL ON TABLES TO learnpg_admin;
